config/routes.rb
Rails.application.routes.draw do
  resources :products, only: [:show, :index]
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "products#index"
  devise_scope :user do
    get  'sign_out', to: 'devise/sessions#destroy', as: :signout
  end
  get 'users/auth/:provider/callback', to: 'sessions#create'
  get 'users/auth/failure', to: redirect('/')

end

app/models/product.rb
class Product < ApplicationRecord
    ratyrate_rateable 'visual_effects', 'original_score', 'director', 'custome_design'
    def poster
        "http://oi63.tinypic.com/#{image_url}"
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h4 class="column">Products</h4>
<div class="column">
  <ul class="products-grid no-bullet row">
    <% @products.each do |product| %>
      <li class="large-3 medium-4 small-12 column">
        <div class="product-card padly">
          <%= link_to product, class: "image" do %>
            <%= image_tag product.image %>
          <% end %>
          <div class="product-info ell glassy-bg padmy padlx">
            <div class="name">
              <h6><%= product.name %> </h6>
            </div>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="large-3 small-12 column">
  <%=image_tag @product.image%>
</div>

<div class="large-9 small-12 column">
  <h3>
    <%= @product.name %>
  </h3>
  <div class="row">
  <div class="small-2 large-2 columns">
    <%= imdb_style_rating_for @product, current_user%>
  </div>
  <br>
  <div class="small-2 large-4 columns">
    <% if current_user %>
      Visual Effects: <%= rating_for @product, "visual_effects" %>
      <br>
      Original Score: <%= rating_for @product, "original_score" %>
      <br>
      Director: <%= rating_for @product, "original_score" %>
      <br>
      Custome Design: <%= rating_for @product, "custome_design" %>
    <% end %>
  </div>
</div>
  <p><%= @product.description %></p>
</div>